### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by ashleypng** [wfmackey/absmapsdata#31]
Hi Will!

I seem to have a download error using the remotes::install_github command

> remotes::install_github("wfmackey/absmapsdata")

Downloading GitHub repo wfmackey/absmapsdata@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/wfmackey/absmapsdata/tarball/HEAD' failed

**Comment by wfmackey** [comment]
Hi @ashleypng ! I can't seem to recreate your error. It looks to be an issue with how your server is working with `remotes`. You can see more details here: https://github.com/r-lib/remotes/issues/130

My guess would be to restart R and try again!

**Comment by ashleypng** [comment]
Thanks Will!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nerskin** [comment]
I hit this issue when I tried to install today, and someone else mentioned not being able to install `absmapsdata` on runapp recently, so I think there is an actual problem here.

The cause seems to be that the package is monstrously large and download.file times out after 60s. Changing the timeout option to a larger value fixes it for me

**Comment by ashleypng** [comment]
Thanks Nicholas.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
